name: DrSleep
version: ${project.version}
main: org.acornmc.drsleep.DrSleep
api-version: 1.15
authors: [DrBot]
description: A fair sleeping solution
commands:
  nosleep:
    description: Adds you to the nosleep list
    usage: /<command>
  drsleep:
    description: DrSleep admin commands
    usage: /<command> <reload|clear|list>
permissions:
  drsleep.list:
    description: list the player's on nosleep
    default: false

